### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by annalhq** [annalhq/algoscope#1]
- [x] Create homepage @annalhq 
- [x] Add sidenav to website @annalhq 
- [x] Create playground layout @annalhq 
- [ ] Algorithm functions in JS/TS 
- [x] Homepage @Nak3011 
- [ ] Hashing introduction @AtharvaKulkarni07
